export type RootStackParamList = {
  Splash:   undefined;
  Login:    undefined;
  Register: undefined;
  Otp:                 { phone?: string; email: string; returnTo?: any } | undefined;
  ForgotPassword:      { returnTo?: any } | undefined;
  ResetPassword:       { email: string; returnTo?: any } | undefined;
  Location:            undefined;
  MainTabs:            undefined;
  ShopDetail:          { shopId: string; shopDetails?: any };
  TimeSlotSelection:   { shopId: string; shopName: string; tenant: string; serviceDetails: string; serviceTitle: string; price: number; businessHours?: any[] };
  PetDetails:          { shopId: string; shopName: string; tenant: string; serviceDetails: string; serviceTitle: string; price: number; date: string; time: string };
  Payment:             { shopId: string; shopName: string; tenant: string; serviceDetails: string; serviceTitle: string; date: string; time: string; price: number; bookingId: string };
  BookingConfirmation: { shopId: string; shopName: string; serviceTitle: string; date: string; time: string; amount: number; bookingId: string };
  UpdateProfile:       { userData?: any };
  AdminLogin:          undefined;
  AdminDashboard:      undefined;
  TodaysAppointments:  undefined;
  BlockSlot:           undefined;
  About:               undefined;
  Settings:            undefined;
  SavedShops:          undefined;
  Search:              undefined;
  Notifications:       undefined;
};
