export type RootStackParamList = {
  Splash:   undefined;
  Login:    undefined;
  Register: undefined;
  Otp:                 { phone?: string; email: string; returnTo?: any } | undefined;
  ForgotPassword:      { returnTo?: any } | undefined;
  ResetPassword:       { email: string; returnTo?: any } | undefined;
  Location:            undefined;
  MainTabs:            undefined;
  ShopDetail:          { shopId: string; shopDetails?: any };
  TimeSlotSelection:   { shopId: string; shopName: string; tenant: string; serviceDetails: string; serviceTitle: string; price: number; businessHours?: any[]; applicableSpecies?: string[] };
  PetDetails:          { shopId: string; shopName: string; tenant: string; serviceDetails: string; serviceTitle: string; price: number; date: string; time: string; applicableSpecies?: string[] };
  Payment:             { shopId: string; shopName: string; tenant: string; serviceDetails: string; serviceTitle: string; date: string; time: string; price: number; bookingId: string };
  BookingConfirmation: { shopId: string; shopName: string; serviceTitle: string; date: string; time: string; amount: number; bookingId: string };
  UpdateProfile:       { userData?: any };
  About:               undefined;
  Settings:            undefined;
  SavedShops:          undefined;
  Search:              undefined;
  Notifications:       undefined;
  PaymentHistory:      undefined;
  BookingFailed:       { bookingId: string };
  BookingDetail:       { bookingData: any };
  HelpCenter:          undefined;
  WebViewScreen:       { url: string; title?: string };
};
